package(default_visibility = ["//visibility:public"])

licenses([
    "notice",
])

alias(
    name = "bytes",
    actual = "@raze__bytes__1_1_0//:bytes",
    tags = [
        "cargo-raze",
        "manual",
    ],
)

alias(
    name = "serde",
    actual = "@raze__serde__1_0_118//:serde",
    tags = [
        "cargo-raze",
        "manual",
    ],
)

alias(
    name = "near_sdk",
    actual = "@raze__near_sdk__4_0_0_pre_4//:near_sdk",
    tags = [
        "cargo-raze",
        "manual",
    ],
)

alias(
    name = "rustc_hex",
    actual = "@raze__rustc_hex__2_1_0//:rustc_hex",
    tags = [
        "cargo-raze",
        "manual",
    ],
)

alias(
    name = "rlp_derive",
    actual = "@raze__rlp_derive__0_1_0//:rlp_derive",
    tags = [
        "cargo-raze",
        "manual",
    ],
)

exports_files(
    [
        "crates.bzl",
    ],
    visibility = ["//visibility:public"],
)
