#!/bin/sh
set -e

if [ ! -d $BSC_DATADIR/geth/chaindata ]; then
    echo "$0: creating $BSC_DATADIR"
    mkdir -p "$BSC_DATADIR"
    chmod 700 "$BSC_DATADIR"
    echo "$0: initiating blockchain"
    cp -rf $BSC_HOME/keystore $BSC_DATADIR/keystore
    geth --datadir "$BSC_DATADIR" init $BSC_HOME/genesis.json
fi

echo "$0: setting data directory to $BSC_DATADIR"

# allow exiting using CTRL + C
exit_func() {
    echo "Exiting..."
    exit 1
}

trap exit_func SIGTERM SIGINT

# 150 is an arbitrary choice, which seems good enough
#stty cols 150
exec geth --config $BSC_HOME/config.toml \
   --datadir $BSC_DATADIR --verbosity 3 --mine \
   --unlock 0x48948297C3236ec3eA6c95f4eEc22fDb18255E55 --password .secret \
   --miner.etherbase 0x48948297C3236ec3eA6c95f4eEc22fDb18255E55