version: "3.9"
x-common-args: &common-args
    GOLOOP_IMAGE: iconloop/goloop-icon:v0.9.9
services:
    gochain:
        container_name: gochain
        build:
            context: ./gochain
            args: 
                - GOCHAIN_IMAGE=goloop/gochain-icon:0.9.9
        logging:
            driver: none
        volumes:
            - ${PWD}/config:/gochain/config
            - ${PWD}/data/gochain:/gochain/data
        ports:
            - 9080:9080
    moonbeam:
        container_name: g2m_moonbeam
        build:
            context: ./moonbeam
            args:     
                MOONBEAM_VERSION: v0.9.6
        logging:
            driver: none
        volumes:
            - ${PWD}/data/moonbase_dev:/data/chains/moonbase_dev
        ports:
            - "9933:9933"
            - "9944:9944"
        command: ['--dev', '--ws-external', '--rpc-external', '--rpc-cors', 'all', '--base-path', '/data', '--ethapi', 'debug', '--sealing', '3000']
    btp_icon:
        container_name: g2m_btp_icon
        build:
            context: .
            args: *common-args
        depends_on: 
            gochain:
                condition: service_healthy
            moonbeam:
                condition: service_healthy
        volumes: 
            - ./scripts:/btpsimple/scripts
            - ${PWD}/config:/btpsimple/config
            - ${PWD}/data/btpsimple_icon:/btpsimple/data
        healthcheck:
            test: ["CMD", "test",  "-f", "/btpsimple/config/provision.started"]
            interval: 3s
            timeout: 3s
            retries: 10
        environment: 
            - GOLOOPCHAIN=gochain
            - RELAY_ENDPOINT=wss://kusama-rpc.polkadot.io
            - PARA_ENDPOINT=ws://moonbeam:9944
            - MOONBEAM_RPC_URL=http://moonbeam:9933
            - RELAY_CHAIN_OFFSET=8511058
            - BTPSIMPLE_BASE_DIR=/btpsimple/data/btpsimple_icon
            - BTPSIMPLE_CONFIG=/btpsimple/config/config.icon.json
            - BTPSIMPLE_SRC_ADDRESS=/btpsimple/config/btp.icon
            - BTPSIMPLE_SRC_ENDPOINT=http://gochain:9080/api/v3/icon
            - BTPSIMPLE_DST_ADDRESS=/btpsimple/config/btp.moonbeam
            - BTPSIMPLE_DST_ENDPOINT=http://moonbeam:9933
            - BTPSIMPLE_OFFSET=/btpsimple/config/offset.icon
            - BTPSIMPLE_KEY_STORE=/btpsimple/config/moonbeam.keystore.json
            - BTPSIMPLE_KEY_SECRET=/btpsimple/config/moonbeam.keysecret
            - BTPSIMPLE_LOG_WRITER_FILENAME=/btpsimple/data/btpsimple_icon/btp.icon.log
    btp_moonbeam:
        container_name: g2m_btp_moonbeam
        build:
            context: .
            args: *common-args
        depends_on: 
            btp_icon:
                condition: service_healthy
        volumes: 
            - ./scripts:/btpsimple/scripts
            - ${PWD}/config:/btpsimple/config
            - ${PWD}/data/btpsimple_moonbeam:/btpsimple/data
        environment: 
            - GOLOOPCHAIN=gochain
            - RELAY_ENDPOINT=wss://kusama-rpc.polkadot.io
            - PARA_ENDPOINT=ws://moonbeam:9944
            - MOONBEAM_RPC_URL=http://moonbeam:9933
            - RELAY_CHAIN_OFFSET=8511058
            - BTPSIMPLE_BASE_DIR=/btpsimple/data/btpsimple_moonbeam
            - BTPSIMPLE_CONFIG=/btpsimple/config/config.moonbeam.json
            - BTPSIMPLE_SRC_ADDRESS=/btpsimple/config/btp.moonbeam
            - BTPSIMPLE_SRC_ENDPOINT=http://moonbeam:9933
            - BTPSIMPLE_DST_ADDRESS=/btpsimple/config/btp.icon
            - BTPSIMPLE_DST_ENDPOINT=http://gochain:9080/api/v3/icon
            - BTPSIMPLE_DST_OPTIONS="stepLimit=5000000000"
            - BTPSIMPLE_OFFSET=/btpsimple/config/offset.moonbeam_parachain
            - BTPSIMPLE_KEY_STORE=/btpsimple/config/gochain.keystore.json
            - BTPSIMPLE_KEY_SECRET=/btpsimple/config/gochain.keysecret
            - BTPSIMPLE_LOG_WRITER_FILENAME=/btpsimple/data/btpsimple_moonbeam/btpsimple_moonbeam.log