#!/bin/sh
set -e

if [ "$GOLOOP_CONFIG" != "" ] && [ ! -f "$GOLOOP_CONFIG" ]; then
    UNSET="GOLOOP_CONFIG"
    CMD="goloop server save $GOLOOP_CONFIG"
    if [ "$GOLOOP_KEY_SECRET" != "" ] && [ ! -f "$GOLOOP_KEY_SECRET" ]; then
        mkdir -p $(dirname $GOLOOP_KEY_SECRET)
        echo -n $(date|md5sum|head -c16) > $GOLOOP_KEY_SECRET
    fi
    if [ "$GOLOOP_KEY_STORE" != "" ] && [ ! -f "$GOLOOP_KEY_STORE" ]; then
        UNSET="$UNSET GOLOOP_KEY_STORE"
        CMD="$CMD --save_key_store=$GOLOOP_KEY_STORE"
    fi
    sh -c "unset $UNSET ; $CMD"
fi

source /provision.sh

provision

source /goloop/venv/bin/activate
if [ "${GOLOOP_LOGFILE}" != "" ]; then
    GOLOOP_LOGDIR=$(dirname ${GOLOOP_LOGFILE})
    if [ ! -d "${GOLOOP_LOGDIR}" ]; then
        mkdir -p ${GOLOOP_LOGDIR}
    fi
    exec "$@ 2>&1 | tee -a ${GOLOOP_LOGFILE}"
else
    exec "$@"
fi