// Code generated by mockery v2.0.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DataError is an autogenerated mock type for the DataError type
type DataError struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *DataError) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ErrorData provides a mock function with given fields:
func (_m *DataError) ErrorData() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
